### ISSUE TITLE
Max character limit for authors and towns and should be 10 instead of 9.

### ISSUE THREAD

**Issue by cpuSonicatt** [Thulinma/ACNLPatternTool#7]
For some reason, this is 9? My name on AC is 'Jacqueline' so I can't fit it into the author field in the pattern details.

**Comment by Thulinma** [comment]
That's because the QR codes are from ACNL (the previous, 3DS game) and that had a 9 character limit on the names. The format of the codes only has room for 9 characters; there's nothing we can do about that. :-(
It doesn't really matter, because no matter what author information you put there, ACNH will never let you edit patterns imported by QR (the game actively blocks it for imported patterns, regardless of author).
